version: "2"
services:
  postgres:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data/pgdata
  phoenix:
    image: docker.pkg.github.com/fcapovilla/agregat/agregat:latest
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGHOST: postgres
      PGPORT: 5432
      PGDATABASE: agregat
      MIX_ENV: prod
      HOST: localhost
      PORT: 4000
      SECRET_KEY_BASE: CHANGE_ME
    ports:
      - "4000:4000"
    depends_on:
      - postgres

volumes:
  postgres-data:
